name: build-test

on: [push]

jobs:
  buildTest:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm i

      - run: pnpm build
        working-directory: .
